#!/bin/bash

echo "Enter a number or a character "
read char

case $char in 
	[a-z] | [A-Z] ) echo "You have entered an alphabet"
			;;
	[0-9] ) echo "you have entered a digit"
			;;
	* ) echo "you have entered neither a number nor a character"
esac


