#!/bin/bash

for filename in $@ ; do 
	result=
if [ -f $filename ] ; then
	echo "\"$filename\" is regular file"
else
if [ -d $filename ] ; then
	echo "\"$filename\" is a directory"
fi
fi
if [ -w $filename ] ; then
	echo "\"$filename\" is a writable"
fi

done 
